version: "3.7"
services:
  bitcoin-in-action-youtube:
    container_name: bitcoin-in-action-youtube
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./datadir:/root/.bitcoin
      - ./Utility:/opt/Utility
      - ./Bitcoin-in-Action:/opt/Bitcoin-in-Action
    ports:
      - "18443:18443"
      - "18444:18444"
    entrypoint: ["/entrypoint.sh"]
    networks:
      - mynetwork 

  explorer:
    container_name: btc-rpc-explorer
    environment:
      BTCEXP_HOST: 0.0.0.0
      BTCEXP_BITCOIND_HOST: bitcoin-in-action-youtube
      BTCEXP_BITCOIND_COOKIE: /shared_data/regtest/.cookie
      BTCEXP_BITCOIND_PORT: 18443      
    build:
      context: ./
    image: btc-rpc-explorer:latest
    ports:
      - "3002:3002"
    volumes:
      - ./datadir:/shared_data  
    networks:
      - mynetwork 
    depends_on:
      - bitcoin-in-action-youtube  

networks:
  mynetwork:
    driver: bridge
